export const SET_SKIN = "SET_SKIN";
export const UPDATE_SKIN = "UPDATE_SKIN";

export const SET_CONTACT = "SET_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";

export const SET_EDUCATION = "SET_EDUCATION";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";

export const SET_EXPERIENCE = "SET_EXPERIENCE";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";

export const SET_SKILL = "SET_SKILL";
export const UPDATE_SKILL = "UPDATE_SKILL";